### ISSUE TITLE
Recipes table creation for database

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-backend#9]
Related issue #8
Need to confirm the model for a Recipe record and its relating tables. Create new issues if new extra tables in relation to this are required to be designed.

**Comment by hel1o-w0rld** [comment]
> Related issue #8 Need to confirm the model for a Recipe record and its relating tables. Create new issues if new extra tables in relation to this are required to be designed.

After thinking about the structure of recipes, I think it would be better to use ducument-oriented database for that.

For example, we can either store the file location of json file in MySQL or use other nosql DBMS.
